### ISSUE TITLE
Bulk async operations

### ISSUE THREAD

**Issue by pauliusrum** [jillesvangurp/es-kotlin-wrapper-client#7] opened 2019-10-02 10:55 UTC
Now it is only possible to use index async operation in bulkAsync witthout explicit `runBlocking` block:

```kotlin
 dao.bulkAsync(
            bulkSize = bulkSize,
            refreshPolicy = WriteRequest.RefreshPolicy.NONE
        ) {
            index(..)  // Ok because internally it uses sendBlocking
            delete(..) // Not ok because delete is a suspending function
        }
```

I think that `bulkAsync` operation should be a coroutine and all operations (index, delete, etc..) should be suspending because using `sendBlocking` kinda defeats the purpose of async. I'm not very familiar with the internals of bulk operations so it would be nice to hear our opinion.

**Comment by jillesvangurp** [comment] 2019-10-04 09:58
Thanks for filing this.

`io.inbot.eskotlinwrapper.IndexDAO#bulkAsync` is already marked as suspend.
`io.inbot.eskotlinwrapper.AsyncBulkIndexingSession#delete` is not suspend in the latest version; I think this was a bug I left the upcoming release will fix this.

The reason index, delete, etc. are not suspend is because they are called from non suspend lambdas and use the sendBlocking on a channel.

I've experimented with making everything suspend but can't get it to compile. The problem is getting access to the co-routine scope from lambdas that are not suspend. I've not figured out  a clean way to do it. You can mark lamdas as suspend but then calling them from another lambda that is not suspend (like the lamdbas in the `Flow` API) becomes an issue.

The design for is still a bit in flux as some of the documentation for co-routines and flow are a bit of a mind fuck and Flow was only just released. My intention with this was to get some controllable level of parallelism with the number of in flight bulk requests but it seems that everything is happening sequentially.  If you have any ideas for improving this, I'd welcome a PR. I've been thinking of getting rid of Flow as it seems a bit limiting for this.

**Comment by jillesvangurp** [comment] 2019-12-24 16:15
Delete is no longer suspend in the latest release. I may at some point change the underlying implementation to allow for proper suspend lambda & operations.

**Closed by jillesvangurp** 2019-12-24 16:15 UTC
